### PR TITLE
Merge and split ghosts

### PR DESCRIPTION
**Pull request by costas-basdekis**
Add the ability to merge and split ghosts as well

I've added the `is_ghost` attribute to the `on_chest_merged` and `on_chest_split` events

### CODE REVIEW

**Comment by Atria1234** [comment]
Nice work, I'll check if ghost entity merging works with circuit network and general testing.

Thanks for your contribution

**Comment by costas-basdekis** [comment]
You're welcome!

Nice catch, I forgot to check for connections. I've now included re-adding the connections, and it looks like it's working properly.

**Comment by Atria1234** [comment]
Last thing would be setting the "red bar"...but it turns out the bar has to be set during entity creation for ghosts as they don't have inventory I could access.

**Comment by Atria1234** [comment]
Oh, I was concentrating on how to set the `bar` that it didn't occur to me that it will be more problematic to read it.

**Comment by costas-basdekis** [comment]
Another good point I missed!

It seems like you can't read it nor write it. I stumbled upon [LuaEntity.copy_settings](https://lua-api.factorio.com/latest/classes/LuaEntity.html#copy_settings), which allows us to copy the settings to another chest.

The only problem is that we need to create a dummy chest of the same size to be able to copy these settings and read from or write to the inventory bar. I created a method where I create a chest at some offset from the chest, but this obviously depends on the chest being able to be placed there, which it might not have empty ground.

This is the code I wrote:
```lua
function MergingChests.move_ghost_inventory_bar(from_entities, to_entities)
	local bar_count = 0
	for _, ghost in ipairs(from_entities) do
		local dummy = ghost.surface.create_entity({
			name = ghost.ghost_name,
			-- TODO: Either try a few different positions, or use an empty surface
			position = { x = ghost.position.x + 1000, y = ghost.position.y },
			force = ghost.force,
			raise_built = false,
		})
		if dummy then
			dummy.copy_settings(ghost)
			local inventory = dummy.get_inventory(defines.inventory.chest)
			if inventory and inventory.supports_bar() then
				bar_count = bar_count + inventory.get_bar() - 1
			end
			dummy.destroy({ raise_destroy = false })
		end
	end

	if bar_count == 0 then
		return
	end

	local to_entities_count = table_size(to_entities)
	for _, ghost in ipairs(to_entities) do
		local dummy = ghost.surface.create_entity({
			name = ghost.ghost_name,
			position = { x = ghost.position.x + 1000, y = ghost.position.y },
			force = ghost.force,
			raise_built = false,
		})
		if dummy then
			local inventory = dummy.get_inventory(defines.inventory.chest)
			if inventory and inventory.supports_bar() then
				local bar = math.min(fmath.round(bar_count / to_entities_count), 65535)
				inventory.set_bar(bar + 1)
				ghost.copy_settings(dummy)
				dummy.destroy({ raise_destroy = false })
				bar_count = bar_count - bar
				to_entities_count = to_entities_count - 1
			end
			dummy.destroy({ raise_destroy = false })
		end
	end
end
```

An option would be to create a create a temporary surface to create the entities each time we merge/split, or to create a persistent surface at the beginning of the load to do this kind of operation.

**Comment by Atria1234** [comment]
AFAIK entities can overlap, so it might be possible to build non ghost entity on the same spot, copy settings and then clean up. But I'm starting to worry about code duplication

**Comment by costas-basdekis** [comment]
Ah, didn't realise you could have them overlap. I can try that.

Do you mean duplication in the `on_player_alt_selected_area` methods? I was thinking that I could tidy them up to have less duplication.

Another question I just thought about: do you split/merge logistical requests?

**Comment by Atria1234** [comment]
That's how the merging/splitting works. New entity(ies) are created on their final spot and then inventory is copied, circuit reconnected, bar set. And only then the old entity(ies) are deleted.

Yes, logistic requests are handled in WideChestsLogistic mod. Depending on the mod setting

**Comment by costas-basdekis** [comment]
So it appears that creating an entity on top of a ghost deletes the ghosts underneath it.

So creating a dummy somewhere else in order to copy it is not an issue, even if it overlaps with other entities, but it would delete any ghosts that might be sitting there.

What we could do is pick a location (e.g. (10000, 10000)) to create the dummy, check to see if there are any ghosts underneath, and if there are, try another location, perhaps randomised. What do you think?

**Comment by Atria1234** [comment]
Placing the entity in random place on the map doesn't sound great. Especially if you would need to check if the location exist and is empty. It would be better to have separate surface for that like you suggested before. And then clean up after every chest is merged/split.

It's getting kind of complex 😟

**Comment by Atria1234** [comment]
Pushed proposed changes with new surface, what do you think? From the testing I did it feels ready to be released

**Comment by costas-basdekis** [comment]
Nice, thank you!

Didn't realise you can set the `bar` on entity creation, that makes things much easier.

Looks good to me!

**Pull request merged**
